### ISSUE TITLE
Montage-3103b.v2 suggestion: avoid dev_err on address detection

### ISSUE THREAD

**Issue by JMS-1** [b-rad-NDi/media_tree#10]
With kernel 5.7 in each boot you find the "errror" message: _m88ds3103 5-006a: dt addr is 0x21_

I think your use of **dvb_err** is unintentional and perhaps you should lower the severity a bit: _dev_err(&client->dev, "dt addr is 0x%02x", dev->dt_addr);_ [drivers/media/dvb-frontends/m88ds3103.c line 1904].

In addition your fix still works like a charm!

**Comment by micha137** [comment]
Yes, sorry. Someone already fixed this here: https://git.linuxtv.org/media_tree.git/commit/?id=c77591a8ca5ad843238df67f89a1bdc0ee7dbb76
