### ISSUE TITLE
Support for TerraTec Electronic GmbH Cinergy S2 Box ID 0ccd:0105 with Montage-3103b

### ISSUE THREAD

**Issue by ghost** [b-rad-NDi/media_tree#2]
Hi, my device is TerraTec Electronic GmbH Cinergy S2 Box ID 0ccd:0105 with Montage-3103b

informations on kernel without drivers (media_build)

lsusb:

Bus 001 Device 002: ID 0ccd:0105 TerraTec Electronic GmbH Cinergy S2 Box

dmesg :

[ 1249.760585] usb 1-1: new high-speed USB device number 4 using ehci-pci
[ 1249.890023] usb 1-1: New USB device found, idVendor=0ccd, idProduct=0105, bcdDevice= 0.00
[ 1249.890026] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1249.890029] usb 1-1: Product: TERRATEC USB Tuner
[ 1249.890031] usb 1-1: Manufacturer: Tevii
[ 1249.890033] usb 1-1: SerialNumber: 000000031

informations on kernel with drivers (media_tree) from linuxtv brad repo

ls -l /dev/dvb/adapter0 :

razem 0
crw-rw----+ 1 root video 212, 4 11-08 15:59 demux0
crw-rw----+ 1 root video 212, 5 11-08 15:59 dvr0
crw-rw----+ 1 root video 212, 7 11-08 15:59 net0

frontend is missing :

> "[   33.279671] m88ds3103 0-0068: Unknown device. Chip_id=52"

[   27.252906] usb 1-1: USB disconnect, device number 2
[   27.262960] dvb-usb: Terratec Cinergy S2 USB BOX successfully deinitialized and disconnected.
[   32.830356] usb 1-1: new high-speed USB device number 4 using ehci-pci
[   32.959923] usb 1-1: New USB device found, idVendor=0ccd, idProduct=0105, bcdDevice= 0.00
[   32.959926] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   32.959929] usb 1-1: Product: TERRATEC USB Tuner
[   32.959931] usb 1-1: Manufacturer: Tevii
[   32.959933] usb 1-1: SerialNumber: 000000031
[   32.960354] dw2102: su3000_identify_state
[   32.960355] dvb-usb: found a 'Terratec Cinergy S2 USB BOX' in warm state.
[   32.960365] dw2102: su3000_power_ctrl: 1, initialized 0
[   32.962060] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[   32.962188] dvbdev: DVB: registering new adapter (Terratec Cinergy S2 USB BOX)
[   32.962194] usb 1-1: media controller created
[   32.966918] dvb-usb: MAC address: bc:ea:2b:46:13:a5
[   32.967297] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[   33.279671] m88ds3103 0-0068: Unknown device. Chip_id=52
[   33.279778] dvb-usb: no frontend was attached by 'Terratec Cinergy S2 USB BOX'
[   33.280302] Registered IR keymap rc-tt-1500
[   33.280365] rc rc0: Terratec Cinergy S2 USB BOX as /devices/pci0000:00/0000:00:04.1/usb1/1-1/rc/rc0
[   33.280445] input: Terratec Cinergy S2 USB BOX as /devices/pci0000:00/0000:00:04.1/usb1/1-1/rc/rc0/input6
[   33.281696] rc rc0: lirc_dev: driver dw2102 registered at minor = 0, scancode receiver, no transmitter
[   33.281698] dvb-usb: schedule remote query interval to 250 msecs.
[   33.281701] dw2102: su3000_power_ctrl: 0, initialized 1
[   33.281702] dvb-usb: Terratec Cinergy S2 USB BOX successfully initialized and connected.

lsmod:

Module                  Size  Used by
dvb_usb_dvbsky         20480  0
dvb_usb_v2             28672  1 dvb_usb_dvbsky
rc_tt_1500             16384  0
m88ds3103              28672  1 dvb_usb_dvbsky
i2c_mux                16384  1 m88ds3103
dvb_usb_dw2102         69632  0
dvb_usb                28672  1 dvb_usb_dw2102
dvb_core              126976  5 dvb_usb_v2,m88ds3103,dvb_usb,dvb_usb_dw2102,dvb_usb_dvbsky
rc_core                40960  6 dvb_usb_v2,dvb_usb,dvb_usb_dw2102,dvb_usb_dvbsky,rc_tt_1500
mc                     40960  3 dvb_usb_v2,dvb_usb,dvb_core

module dvb_usb_dw2102 is not used with module m88ds3103 !
module m88ds3103 is used with module dvb_usb_dvbsky !

is there any option to pass m88ds3103 module load for 3103b version ?
is this lsmod is correct because dvb_usb_dw2102 is not used with module m88ds3103 ?
why this device is recognized at once by dw2102 and dvbsky/ blacklist first or second ?

is there any chance to add support for this device to your brantch Montage_3103b ?
or is already included but something is not configured ?

https://git.linuxtv.org/brad/media_tree.git/log/?h=Montage-3103b.v2

**Comment by ghost** [comment]
Hi , I've crated Pull request for chanege in dvb-usb-ids.h 
https://github.com/b-rad-NDi/media_tree/pull/3

**Comment by NukeMania** [comment]
try this patch 
https://pastebin.com/W05fpMRr

**Comment by ghost** [comment]
Thx @NukeMania , after i've check this patch with montage3103b-v2.patch on clean media_build from linuxtv master i report if works.

**Comment by ghost** [comment]
sorry @NukeMania but this patch is not 100% ok for terratec cinergy s2 rev.4 3103b.
I've compiled this patch with  montage3103b support patch on media_build from linuxtv master git repo but this is  not working solution for proper recognition Monatage demod on this device. Unknow "chip id" and lsmod showing module dvb_usb_dv2102 is not paired with m88ds3103 ...

**Comment by ghost** [comment]
i've also tray compile dvbsky.c with this changes but :

ts@ts-GA-73PVM-S2H:~$ dmesg |grep dvb
[    4.181157] usb 1-2: dvb_usb_v2: found a 'Terratec Cinergy S2 Rev.4' in warm state
[    4.181317] usb 1-2: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
[    4.181340] dvbdev: DVB: registering new adapter (Terratec Cinergy S2 Rev.4)
[    4.193161] usb 1-2: dvb_usb_v2: MAC address: ff:ff:ff:ff:ff:ff
[    4.194176] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[    4.397656] RIP: 0010:dvb_module_release+0x1a/0x30 [dvb_core]
[    4.397688]  dvbsky_frontend_detach+0x47/0x80 [dvb_usb_dvbsky]
[    4.397693]  dvb_usbv2_exit+0x169/0x390 [dvb_usb_v2]
[    4.397697]  dvb_usbv2_probe+0x1b9/0x200 [dvb_usb_v2]
[    4.397736]  dvbsky_usb_driver_init+0x23/0x1000 [dvb_usb_dvbsky]
[    4.397789] Modules linked in: irqbypass mxm_wmi snd_seq(+) ts2020(OE) video input_leds ttm snd_seq_device serio_raw wmi_bmof drm_kms_helper dvb_usb_dvbsky(OE+) snd_timer dvb_usb_v2(OE) m88ds3103(OE) dvb_core(OE) i2c_mux drm videobuf2_vmalloc(OE) videobuf2_memops(OE) mac_hid snd videobuf2_common(OE) videodev(OE) mc(OE) rc_core(OE) i2c_algo_bit fb_sys_fops syscopyarea sysfillrect sysimgblt soundcore sch_fq_codel parport_pc ppdev lp parport ip_tables x_tables autofs4 firewire_ohci pata_acpi psmouse forcedeth firewire_core crc_itu_t ahci pata_amd i2c_nforce2 floppy libahci wmi
[    4.397826] RIP: 0010:dvb_module_release+0x1a/0x30 [dvb_core]
