### ISSUE TITLE
Pi4 4.19.75-v7 kernel PCTV 461e

### ISSUE THREAD

**Issue by damianraine** [b-rad-NDi/media_tree#8]
Hello,

I'm after a little help / assistance applying this patch to my raspbian buster (Kernal 4.19.75-v7 )

Any point in the right direction (i.e. tut) would be hugely appreciated

Thanks

**Comment by b-rad-NDi** [comment]
Step one is to follow a guide and be able to compile your own kernel. If you can do that I can provide a patch set for you to apply against.

There are many guides out there you can follow. Lemme know once you're passed that stage.
