### ISSUE TITLE
TerraTec Electronic GmbH Cinergy S2 Box

### ISSUE THREAD

**Issue by NelvinBHV** [b-rad-NDi/media_tree#9]
I have a TerraTec Electronic GmbH Cinergy S2 Box connect to my Gentoo Linux Box with kernel 4.19.97-gentoo.
The kernel i had patched with these files [https://github.com/devegoo/Monatge_3103b](url) coverted to kernel 4.19.97-gentoo.
Patch dw2102.c https://pastebin.com/a7AP9T06
Patch m88ds3103.c https://pastebin.com/scvt0wVr
Patch m88ds3103_priv.h https://pastebin.com/mekJZAuA

The driver load all related modules: 
[dvb.log](https://github.com/b-rad-NDi/media_tree/files/4282512/dvb.log)

But if i start tvheadend or w_scan nothing works. 
The log file is full of:
dw2102: i2c read request failed: i2c status 7

I tried a 5.5 kernel and a 5.6-rc1 kernel. Everytime the same result.
How i can fix it?

**Comment by NelvinBHV** [comment]
I also tried the tree Montage-3103b.v3 with also the same error result

**Comment by NelvinBHV** [comment]
Mar  7 08:37:13 WG-DC01 kernel: [  801.263696] dw2102: su3000_identify_state
Mar  7 08:37:13 WG-DC01 kernel: [  801.263701] dvb-usb: found a 'Terratec Cinergy S2 USB BOX' in warm state.
Mar  7 08:37:13 WG-DC01 kernel: [  801.263709] dw2102: su3000_power_ctrl: 1, initialized 0
Mar  7 08:37:13 WG-DC01 kernel: [  801.263850] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
Mar  7 08:37:13 WG-DC01 kernel: [  801.264206] dvbdev: DVB: registering new adapter (Terratec Cinergy S2 USB BOX)
Mar  7 08:37:13 WG-DC01 kernel: [  801.268288] dvb-usb: MAC address: bc:ea:2b:46:13:a5
Mar  7 08:37:13 WG-DC01 kernel: [  801.578002] dw2102: tt_s2_4600_frontend_attach: attaching demodulator of type m88ds3103b at i2c address 0x6a
Mar  7 08:37:13 WG-DC01 kernel: [  801.585385] i2c i2c-0: Added multiplexed i2c bus 1
Mar  7 08:37:13 WG-DC01 kernel: [  801.586995] m88ds3103 0-006a: dt addr is 0x21
Mar  7 08:37:13 WG-DC01 kernel: [  801.649771] ts2020 1-0060: Montage Technology TS2022 successfully identified
Mar  7 08:37:13 WG-DC01 kernel: [  801.649829] usb 3-2: DVB: registering adapter 0 frontend 0 (Montage Technology M88RS6000)...
Mar  7 08:37:13 WG-DC01 kernel: [  801.673819] Registered IR keymap rc-tt-1500
Mar  7 08:37:13 WG-DC01 kernel: [  801.673916] rc rc0: Terratec Cinergy S2 USB BOX as /devices/pci0000:00/0000:00:14.0/usb3/3-2/rc/rc0
Mar  7 08:37:13 WG-DC01 kernel: [  801.674073] input: Terratec Cinergy S2 USB BOX as /devices/pci0000:00/0000:00:14.0/usb3/3-2/rc/rc0/input5
Mar  7 08:37:13 WG-DC01 kernel: [  801.674236] dvb-usb: schedule remote query interval to 250 msecs.
Mar  7 08:37:13 WG-DC01 kernel: [  801.674244] dw2102: su3000_power_ctrl: 0, initialized 1
Mar  7 08:37:13 WG-DC01 kernel: [  801.674247] dvb-usb: Terratec Cinergy S2 USB BOX successfully initialized and connected.
Mar  7 08:37:13 WG-DC01 kernel: [  801.674336] usbcore: registered new interface driver dw2102
Mar  7 08:37:47 WG-DC01 kernel: [  836.046285] dw2102: su3000_power_ctrl: 1, initialized 1
Mar  7 08:37:47 WG-DC01 kernel: [  836.051242] m88ds3103 0-006a: found a 'Montage Technology M88DS3103' in cold state
Mar  7 08:37:47 WG-DC01 kernel: [  836.051350] m88ds3103 0-006a: downloading firmware from file 'dvb-demod-m88ds3103b.fw'
Mar  7 08:37:48 WG-DC01 kernel: [  837.100315] m88ds3103 0-006a: found a 'Montage Technology M88DS3103' in warm state
Mar  7 08:37:48 WG-DC01 kernel: [  837.100322] m88ds3103 0-006a: firmware version: 3.7
Mar  7 08:37:48 WG-DC01 kernel: [  837.136354] dw2102: su3000_power_ctrl: 0, initialized 1
Mar  7 08:37:48 WG-DC01 kernel: [  837.136521] dw2102: su3000_power_ctrl: 1, initialized 1
Mar  7 08:37:49 WG-DC01 kernel: [  837.723812] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.756200] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.759053] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.762024] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.850890] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.853573] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.864615] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.867157] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:49 WG-DC01 kernel: [  837.869724] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:51 WG-DC01 kernel: [  840.059754] dw2102: i2c read request failed: i2c status 7
Mar  7 08:37:51 WG-DC01 kernel: [  840.092115] dw2102: i2c read request failed: i2c status 7

**Comment by NelvinBHV** [comment]
Here you find the i2c trace https://pastebin.com/gEeQKiDD

**Comment by stpf99** [comment]
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/tree/master/patches/mainline-extra/tip/80.montage.3103b try this patchset .

**Comment by NelvinBHV** [comment]
Thanks, i will try it

**Comment by NelvinBHV** [comment]
I tried the above patchset, but nothing changed.

**Comment by NukeMania** [comment]
you can try ds3k module from crazycat's media tree 
but you need to enable debug in ds3k.c file so set from 0 to 1 those values  `static int debug = 1; static int debugI2c = 1;` debug info will print in dmesg

probably we share same device which mine doesn't work with ds3103b.v tree too

https://bitbucket.org/CrazyCat/media_build/src/master/

**Comment by stpf99** [comment]
this patches add support for TERRATEC CINERGY BOX /rev.4
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0004-dw2102-probe-for-demodulator-i2c-address.patch
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0005-dw2102-check-initialization-replies.patch
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0006-dw2102-warn-on-failed-i2c-read-requests.patch
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0003-dw2102-Log-probed-demodulator-type-and-address.patch

Try to compile and install this patches with main patch:
https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0001-m88ds3103-Add-Montage-3103b-support.patch

on media_build https://www.linuxtv.org/wiki/index.php/How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers

git clone --depth=1 git://linuxtv.org/media_build.git
cd media_build 
put patches to "backports" dir and edit  backports.txt /add kernel (uname -r) 

["uname -r"]
add 0001-m88ds3103-Add-Montage-3103b-support.patch
add 0006-dw2102-warn-on-failed-i2c-read-requests.patch
add 0005-dw2102-check-initialization-replies.patch
add 0004-dw2102-probe-for-demodulator-i2c-address.patch
add 0003-dw2102-Log-probed-demodulator-type-and-address.patch

./build

**Comment by NelvinBHV** [comment]
> this patches add support for TERRATEC CINERGY BOX /rev.4
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0004-dw2102-probe-for-demodulator-i2c-address.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0005-dw2102-check-initialization-replies.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0006-dw2102-warn-on-failed-i2c-read-requests.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0003-dw2102-Log-probed-demodulator-type-and-address.patch

I used this files...

**Comment by NelvinBHV** [comment]
> > this patches add support for TERRATEC CINERGY BOX /rev.4
> > https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0004-dw2102-probe-for-demodulator-i2c-address.patch
> > https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0005-dw2102-check-initialization-replies.patch
> > https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0006-dw2102-warn-on-failed-i2c-read-requests.patch
> > https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0003-dw2102-Log-probed-demodulator-type-and-address.patch
> 
> I used this files...

All load correct, but i have futher the i2c-error

**Comment by stpf99** [comment]
test this on media_build first not on whole kernel compilation

**Comment by NelvinBHV** [comment]
> this patches add support for TERRATEC CINERGY BOX /rev.4
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0004-dw2102-probe-for-demodulator-i2c-address.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0005-dw2102-check-initialization-replies.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0006-dw2102-warn-on-failed-i2c-read-requests.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0003-dw2102-Log-probed-demodulator-type-and-address.patch
> 
> Try to compile and install this patches with main patch:
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0001-m88ds3103-Add-Montage-3103b-support.patch
> 
> on media_build https://www.linuxtv.org/wiki/index.php/How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers
> 
> git clone --depth=1 git://linuxtv.org/media_build.git
> cd media_build
> put patches to "backports" dir and edit backports.txt /add kernel (uname -r)
> 
> ["uname -r"]
> add 0001-m88ds3103-Add-Montage-3103b-support.patch
> add 0006-dw2102-warn-on-failed-i2c-read-requests.patch
> add 0005-dw2102-check-initialization-replies.patch
> add 0004-dw2102-probe-for-demodulator-i2c-address.patch
> add 0003-dw2102-Log-probed-demodulator-type-and-address.patch
> 
> ./build

I made everything you wrote. Unfortunately, with the same result
Here i start "w_scan -f s -s S19E2"

[   44.451440] dw2102: su3000_power_ctrl: 1, initialized 1
[   44.456248] m88ds3103 0-006a: found a 'Montage Technology M88DS3103B' in cold state
[   44.457007] m88ds3103 0-006a: downloading firmware from file 'dvb-demod-m88ds3103b.fw'
[   45.503665] m88ds3103 0-006a: found a 'Montage Technology M88DS3103B' in warm state
[   45.503672] m88ds3103 0-006a: firmware version: 3.7
[   45.540664] dw2102: su3000_power_ctrl: 0, initialized 1
[   45.540923] dw2102: su3000_power_ctrl: 1, initialized 1
[   46.125980] dw2102: i2c read request failed: i2c status 7
[   46.159334] dw2102: i2c read request failed: i2c status 7
[   46.162204] dw2102: i2c read request failed: i2c status 7
[   46.165162] dw2102: i2c read request failed: i2c status 7
[   46.257685] dw2102: i2c read request failed: i2c status 7
[   46.260660] dw2102: i2c read request failed: i2c status 7
[   46.273436] dw2102: i2c read request failed: i2c status 7
[   46.276410] dw2102: i2c read request failed: i2c status 7
[   46.279433] dw2102: i2c read request failed: i2c status 7
[   47.488134] dw2102: su3000_power_ctrl: 0, initialized 1

**Comment by NelvinBHV** [comment]
> you can try ds3k module from crazycat's media tree
> but you need to enable debug in ds3k.c file so set from 0 to 1 those values `static int debug = 1; static int debugI2c = 1;` debug info will print in dmesg
> 
> probably we share same device which mine doesn't work with ds3103b.v tree too
> 
> https://bitbucket.org/CrazyCat/media_build/src/master/

Even with this drivers i have the same problems

**Comment by NelvinBHV** [comment]
lsusb 
Bus 001 Device 002: ID 0ccd:0105 TerraTec Electronic GmbH Cinergy S2 Box
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0ccd TerraTec Electronic GmbH
  idProduct          0x0105 Cinergy S2 Box
  bcdDevice            0.00
  iManufacturer           1 Tevii
  iProduct                2 TERRATEC USB Tuner
  iSerial                 3 000000031
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x00db
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          4 Default
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x13f2  3x 1010 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       2
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x12d6  3x 726 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       3
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x12ae  3x 686 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       4
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x03ca  1x 970 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       5
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x02ac  1x 684 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       6
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      1 
      bInterfaceProtocol      1 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               3
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x03ac  1x 940 bytes
        bInterval               1
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1

**Comment by NukeMania** [comment]
> 
> 
> > you can try ds3k module from crazycat's media tree
> > but you need to enable debug in ds3k.c file so set from 0 to 1 those values `static int debug = 1; static int debugI2c = 1;` debug info will print in dmesg
> > probably we share same device which mine doesn't work with ds3103b.v tree too
> > https://bitbucket.org/CrazyCat/media_build/src/master/
> 
> Even with this drivers i have the same problems

could you share debug log of ds3k driver

**Comment by NelvinBHV** [comment]
> > > you can try ds3k module from crazycat's media tree
> > > but you need to enable debug in ds3k.c file so set from 0 to 1 those values `static int debug = 1; static int debugI2c = 1;` debug info will print in dmesg
> > > probably we share same device which mine doesn't work with ds3103b.v tree too
> > > https://bitbucket.org/CrazyCat/media_build/src/master/
> > 
> > 
> > Even with this drivers i have the same problems
> 
> could you share debug log of ds3k driver

Ok, it was my mistake. The module ds3k never loaded. How to enable dw2102 to use ds3k?
Here my lsmod:

Module                  Size  Used by
rc_su3000              16384  0
ts2020                 16384  0
ds3000                 20480  0
dvb_usb_dw2102         81920  0
dvb_usb                28672  1 dvb_usb_dw2102
dvb_core              122880  5 dvb_usb_v2,m88ds3103,dvb_usb,dvb_usb_dw2102
videobuf2_vmalloc      16384  1 dvb_core
videobuf2_memops       16384  1 videobuf2_vmalloc
videobuf2_common       45056  1 dvb_core
videodev              192512  1 videobuf2_common
mc                     36864  5 videodev,dvb_usb_v2,dvb_usb,dvb_core,videobuf2_common
rc_core                40960  6 dvb_usb_v2,rc_su3000,dvb_usb,dvb_usb_dw2102

dmesg:
[    2.591021] dw2102: su3000_identify_state
[    2.591022] dvb-usb: found a 'Terratec Cinergy S2 USB HD Rev.4' in warm state.
[    2.591026] dw2102: su3000_power_ctrl: 1, initialized 0
[    2.591370] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[    2.592156] dvbdev: DVB: registering new adapter (Terratec Cinergy S2 USB HD Rev.4)
[    2.592161] usb 1-2: media controller created
[    2.596123] dvb-usb: MAC address: bc:ea:2b:46:13:a5
[    2.596311] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[    2.904115] dw2102: i2c read request failed: i2c status 7
[    2.904289] dw2102: i2c read request failed: i2c status 7
[    2.904292] Invalid probe, probably not a DS3000
[    2.904299] dw2102: su3000_frontend_attach: attaching demodulator of type m88ds3103b at i2c address 0x6a
[    2.911834] i2c i2c-0: Added multiplexed i2c bus 1
[    2.913372] m88ds3103 0-006a: dt addr is 0x21
[    3.022225] ts2020 1-0060: Montage Technology TS2022 successfully identified
[    3.022280] usb 1-2: DVB: registering adapter 0 frontend 0 (Montage Technology M88RS6000)...
[    3.022290] dvbdev: dvb_create_media_entity: media entity 'Montage Technology M88RS6000' registered.
[    3.023343] urandom_read: 6 callbacks suppressed
[    3.023346] random: udevd: uninitialized urandom read (16 bytes read)
[    3.049809] Registered IR keymap rc-su3000
[    3.049859] rc rc0: Terratec Cinergy S2 USB HD Rev.4 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/rc/rc0
[    3.049928] rc rc0: lirc_dev: driver dw2102 registered at minor = 0, scancode receiver, no transmitter
[    3.049982] input: Terratec Cinergy S2 USB HD Rev.4 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/rc/rc0/input2
[    3.050037] dvb-usb: schedule remote query interval to 150 msecs.
[    3.050040] dw2102: su3000_power_ctrl: 0, initialized 1
[    3.050042] dvb-usb: Terratec Cinergy S2 USB HD Rev.4 successfully initialized and connected.
[    3.050077] usbcore: registered new interface driver dw2102

**Comment by stpf99** [comment]
Hi. Try also include this series: 
media: use new API for creating client devices
https://patchwork.kernel.org/project/linux-media/list/?series=199089

with oryginal : https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/tree/master/patches/mainline-extra/tip/80.montage.3103b

**Comment by NelvinBHV** [comment]
> this patches add support for TERRATEC CINERGY BOX /rev.4
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0004-dw2102-probe-for-demodulator-i2c-address.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0005-dw2102-check-initialization-replies.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0006-dw2102-warn-on-failed-i2c-read-requests.patch
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0003-dw2102-Log-probed-demodulator-type-and-address.patch
> 
> Try to compile and install this patches with main patch:
> https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/blob/master/patches/mainline-extra/tip/80.montage.3103b/0001-m88ds3103-Add-Montage-3103b-support.patch
> 
> on media_build https://www.linuxtv.org/wiki/index.php/How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers
> 
> git clone --depth=1 git://linuxtv.org/media_build.git
> cd media_build
> put patches to "backports" dir and edit backports.txt /add kernel (uname -r)
> 
> ["uname -r"]
> add 0001-m88ds3103-Add-Montage-3103b-support.patch
> add 0006-dw2102-warn-on-failed-i2c-read-requests.patch
> add 0005-dw2102-check-initialization-replies.patch
> add 0004-dw2102-probe-for-demodulator-i2c-address.patch
> add 0003-dw2102-Log-probed-demodulator-type-and-address.patch
> 
> ./build

Now everything works. I changed the cable and now all channels are available. I close the issue now
